DATA:
  TRAIN_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_feat_output/spectrum_train_data.pkl"
  VALID_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_feat_output/spectrum_valid_data.pkl"
  TEST_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_feat_output/spectrum_test_data.pkl"
DATA_LOADER:
  NAME: "spectrum_data_loader"
  TRAIN_BATCH_SIZE: 4
  NUM_WORKERS: 0
MODEL:
  NAME: "spectrum_Feat_conv_model"
  SPECTRUM_CHANNEL: 1024
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  MILESTONE: [40,]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 50
  OUTPUT_DIR: "results_second_stage/spectrum_on_feat/01_deep_bimodal_spectrum"
