DATA:
  TRAIN_IMG_DATA: "datasets/second_stage/interpret_cnn_extract/train"
  VALID_IMG_DATA: "datasets/second_stage/interpret_cnn_extract/valid"
  TEST_IMG_DATA: "datasets/second_stage/interpret_cnn_extract/test"
DATA_LOADER:
  NAME: "second_stage_data"
  SECOND_STAGE:
    METHOD: "spectrum"
    TYPE: "feat"
  TRAIN_BATCH_SIZE: 8
  NUM_WORKERS: 8
MODEL:
  NAME: "spectrum_feat_resnet18"
  SPECTRUM_CHANNEL: 512
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  MILESTONE: [5,10]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 15
  OUTPUT_DIR: "results_second_stage/spectrum_on_feat/06_interpret_cnn_spectrum"
