DATA:
  TRAIN_IMG_DATA: "image_data/train_data_face"
  VALID_IMG_DATA: "image_data/valid_data_face"
  TEST_IMG_DATA: "image_data/test_data_face"
MODEL:
  NAME: "se_resnet50"
TRAIN:
  OUTPUT_DIR: "results/face/01_senet_face"
