DATA:
  ROOT: "datasets"
  ANIMALS_TRAIN_IMG_DATA: "udiva_full/train/recordings/animals_recordings_train_img"
  GHOST_TRAIN_IMG_DATA: "udiva_full/train/recordings/ghost_recordings_train_img"
  LEGO_TRAIN_IMG_DATA: "udiva_full/train/recordings/lego_recordings_train_img"
  TALK_TRAIN_IMG_DATA: "udiva_full/train/recordings/talk_recordings_train_img"

  ANIMALS_VAL_IMG_DATA: "udiva_full/val/recordings/animals_recordings_val_img"
  GHOST_VAL_IMG_DATA: "udiva_full/val/recordings/ghost_recordings_val_img"
  LEGO_VAL_IMG_DATA: "udiva_full/val/recordings/lego_recordings_val_img"
  TALK_VAL_IMG_DATA: "udiva_full/val/recordings/talk_recordings_val_img"

  ANIMALS_TEST_IMG_DATA: "udiva_full/test/recordings/animals_recordings_test_img"
  GHOST_TEST_IMG_DATA: "udiva_full/test/recordings/ghost_recordings_test_img"
  LEGO_TEST_IMG_DATA: "udiva_full/test/recordings/lego_recordings_test_img"
  TALK_TEST_IMG_DATA: "udiva_full/test/recordings/talk_recordings_test_img"

  ANIMALS_TRAIN_AUD_DATA: "udiva_full/train/recordings/animals_recordings_train_wav"
  GHOST_TRAIN_AUD_DATA: "udiva_full/train/recordings/ghost_recordings_train_wav"
  LEGO_TRAIN_AUD_DATA: "udiva_full/train/recordings/lego_recordings_train_wav"
  TALK_TRAIN_AUD_DATA: "udiva_full/train/recordings/talk_recordings_train_wav"

  ANIMALS_VAL_AUD_DATA: "udiva_full/val/recordings/animals_recordings_val_wav"
  GHOST_VAL_AUD_DATA: "udiva_full/val/recordings/ghost_recordings_val_wav"
  LEGO_VAL_AUD_DATA: "udiva_full/val/recordings/lego_recordings_val_wav"
  TALK_VAL_AUD_DATA: "udiva_full/val/recordings/talk_recordings_val_wav"

  ANIMALS_TEST_AUD_DATA: "udiva_full/test/recordings/animals_recordings_test_wav"
  GHOST_TEST_AUD_DATA: "udiva_full/test/recordings/ghost_recordings_test_wav"
  LEGO_TEST_AUD_DATA: "udiva_full/test/recordings/lego_recordings_test_wav"
  TALK_TEST_AUD_DATA: "udiva_full/test/recordings/talk_recordings_test_wav"

  TRAIN_LABEL_DATA: "udiva_full/train/label/sessions_train.pkl"
  VALID_LABEL_DATA: "udiva_full/val/label/sessions_val.pkl"
  TEST_LABEL_DATA: "udiva_full/test/label/sessions_test.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_lstm_data_loader_udiva" 
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 8
  VALID_BATCH_SIZE: 4
  NUM_WORKERS: 0
  DATASET_NAME: "UDIVA"
MODEL:
  NAME: "audiovisual_resnet_lstm_udiva"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [100, 200]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 5
  OUTPUT_DIR: "results/demo/unified_frame_images/bimodal_resnet_udiva"
