DATA:
  ROOT: "datasets"
  SESSION: "ANIMALS"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "SMOTE"
  ANIMALS_TRAIN_IMG_DATA: "udiva_tiny/train/recordings/animals_recordings_train_img"
  GHOST_TRAIN_IMG_DATA: "udiva_tiny/train/recordings/ghost_recordings_train_img"
  LEGO_TRAIN_IMG_DATA: "udiva_tiny/train/recordings/lego_recordings_train_img"
  TALK_TRAIN_IMG_DATA: "udiva_tiny/train/recordings/talk_recordings_train_img"

  ANIMALS_VAL_IMG_DATA: "udiva_tiny/val/recordings/animals_recordings_val_img"
  GHOST_VAL_IMG_DATA: "udiva_tiny/val/recordings/ghost_recordings_val_img"
  LEGO_VAL_IMG_DATA: "udiva_tiny/val/recordings/lego_recordings_val_img"
  TALK_VAL_IMG_DATA: "udiva_tiny/val/recordings/talk_recordings_val_img"

  ANIMALS_TEST_IMG_DATA: "udiva_tiny/test/recordings/animals_recordings_test_img"
  GHOST_TEST_IMG_DATA: "udiva_tiny/test/recordings/ghost_recordings_test_img"
  LEGO_TEST_IMG_DATA: "udiva_tiny/test/recordings/lego_recordings_test_img"
  TALK_TEST_IMG_DATA: "udiva_tiny/test/recordings/talk_recordings_test_img"

  ANIMALS_TRAIN_AUD_DATA: "udiva_tiny/train/recordings/animals_recordings_train_wav"
  GHOST_TRAIN_AUD_DATA: "udiva_tiny/train/recordings/ghost_recordings_train_wav"
  LEGO_TRAIN_AUD_DATA: "udiva_tiny/train/recordings/lego_recordings_train_wav"
  TALK_TRAIN_AUD_DATA: "udiva_tiny/train/recordings/talk_recordings_train_wav"

  ANIMALS_VAL_AUD_DATA: "udiva_tiny/val/recordings/animals_recordings_val_wav"
  GHOST_VAL_AUD_DATA: "udiva_tiny/val/recordings/ghost_recordings_val_wav"
  LEGO_VAL_AUD_DATA: "udiva_tiny/val/recordings/lego_recordings_val_wav"
  TALK_VAL_AUD_DATA: "udiva_tiny/val/recordings/talk_recordings_val_wav"

  ANIMALS_TEST_AUD_DATA: "udiva_tiny/test/recordings/animals_recordings_test_wav"
  GHOST_TEST_AUD_DATA: "udiva_tiny/test/recordings/ghost_recordings_test_wav"
  LEGO_TEST_AUD_DATA: "udiva_tiny/test/recordings/lego_recordings_test_wav"
  TALK_TEST_AUD_DATA: "udiva_tiny/test/recordings/talk_recordings_test_wav"

  TRAIN_LABEL_DATA: "udiva_tiny/train/label/sessions_train.pkl"
  VALID_LABEL_DATA: "udiva_tiny/val/label/sessions_val.pkl"
  TEST_LABEL_DATA: "udiva_tiny/test/label/sessions_test.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_lstm_data_loader_udiva" 
  TRANSFORM: "udiva_frame_transforms"
  TRAIN_BATCH_SIZE: 32
  VALID_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
  NUM_WORKERS: 2
  DATASET_NAME: "UDIVA"
  DROP_LAST: False
  PREFETCH_FACTOR: 2
MODEL:
  # NAME: "resnet50_3d_model_udiva" 
  NAME: "audio_resnet_udiva" # UDIVA音频分支: 纯ResNet模型结构
  # NAME: "audiovisual_resnet_lstm_udiva" # UDIVA音频+视觉: ResNet-LSTM模型结构：加入了LSTM层处理视觉分支的图片特征序列
LOSS:
  NAME: "binary_cross_entropy"
SOLVER:
  NAME: "adam"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [50, 100, 200, 300, 400, 500, 540, 550, 560, 570, 580, 590]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 2
  OUTPUT_DIR: "results/demo/unified_frame_images/bimodal_resnet_udiva"
  BIMODAL_OPTION: 2
  LOG_INTERVAL: 3
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
