DATA:
  ROOT: "datasets"
  SESSION: "TALK"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "BorderlineSMOTE"
  ANIMALS_TRAIN_IMG_DATA: "udiva_full/train/recordings/animals_recordings_train_img"
  GHOST_TRAIN_IMG_DATA: "udiva_full/train/recordings/ghost_recordings_train_img"
  LEGO_TRAIN_IMG_DATA: "udiva_full/train/recordings/lego_recordings_train_img"
  TALK_TRAIN_IMG_DATA: "udiva_full/train/recordings/talk_recordings_train_img"

  ANIMALS_VAL_IMG_DATA: "udiva_full/val/recordings/animals_recordings_val_img"
  GHOST_VAL_IMG_DATA: "udiva_full/val/recordings/ghost_recordings_val_img"
  LEGO_VAL_IMG_DATA: "udiva_full/val/recordings/lego_recordings_val_img"
  TALK_VAL_IMG_DATA: "udiva_full/val/recordings/talk_recordings_val_img"

  ANIMALS_TEST_IMG_DATA: "udiva_full/test/recordings/animals_recordings_test_img"
  GHOST_TEST_IMG_DATA: "udiva_full/test/recordings/ghost_recordings_test_img"
  LEGO_TEST_IMG_DATA: "udiva_full/test/recordings/lego_recordings_test_img"
  TALK_TEST_IMG_DATA: "udiva_full/test/recordings/talk_recordings_test_img"

  ANIMALS_TRAIN_AUD_DATA: "udiva_full/train/recordings/animals_recordings_train_wav"
  GHOST_TRAIN_AUD_DATA: "udiva_full/train/recordings/ghost_recordings_train_wav"
  LEGO_TRAIN_AUD_DATA: "udiva_full/train/recordings/lego_recordings_train_wav"
  TALK_TRAIN_AUD_DATA: "udiva_full/train/recordings/talk_recordings_train_wav"

  ANIMALS_VAL_AUD_DATA: "udiva_full/val/recordings/animals_recordings_val_wav"
  GHOST_VAL_AUD_DATA: "udiva_full/val/recordings/ghost_recordings_val_wav"
  LEGO_VAL_AUD_DATA: "udiva_full/val/recordings/lego_recordings_val_wav"
  TALK_VAL_AUD_DATA: "udiva_full/val/recordings/talk_recordings_val_wav"

  ANIMALS_TEST_AUD_DATA: "udiva_full/test/recordings/animals_recordings_test_wav"
  GHOST_TEST_AUD_DATA: "udiva_full/test/recordings/ghost_recordings_test_wav"
  LEGO_TEST_AUD_DATA: "udiva_full/test/recordings/lego_recordings_test_wav"
  TALK_TEST_AUD_DATA: "udiva_full/test/recordings/talk_recordings_test_wav"

  TRAIN_LABEL_DATA: "udiva_full/train/label/sessions_train.pkl"
  VALID_LABEL_DATA: "udiva_full/val/label/sessions_val.pkl"
  TEST_LABEL_DATA: "udiva_full/test/label/sessions_test.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_lstm_data_loader_udiva" 
  TRANSFORM: "udiva_frame_transforms"
  TRAIN_BATCH_SIZE: 16
  VALID_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 1
  DATASET_NAME: "UDIVA"
  DROP_LAST: False
  PREFETCH_FACTOR: 2
MODEL:
  # NAME: "vivit_model_udiva"  # visual: https://github.com/rishikksh20/ViViT-pytorch
  # NAME: "vivit_model3_udiva" # visual: https://github.com/drv-agwl/ViViT-pytorch
  # NAME: "timesformer_udiva"  # visual: https://github.com/facebookresearch/TimeSformer
  NAME: "ssast_udiva"          # audio: https://github.com/YuanGongND/ssast
LOSS:
  NAME: "binary_cross_entropy"
SOLVER:
  NAME: "adam"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  # MILESTONE: [50, 100, 200, 300, 400, 500, 520, 540, 550, 560, 570, 580, 590]
  MILESTONE: [10, 30, 50, 100, 200, 300, 400, 500, 520, 540, 550, 560, 570, 580, 590]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 2
  OUTPUT_DIR: "results/demo/unified_frame_images/ssast_udiva"
  BIMODAL_OPTION: 2
  LOG_INTERVAL: 10
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
  PRE_TRAINED_MODEL: "./pre_trained_weights/SSAST/save_mask01-tiny-f16-t16-epo300-lr0.0005-m400-pretrain_mpc-udiva/models/best_audio_model.pth"
  TASK: "ft_avgtok"
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
