DATA_LOADER:
  NAME: "spatial_temporal_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 8
  NUM_WORKERS: 0
MODEL:
  NAME: "resnet50_3d_model"
TRAIN:
  OUTPUT_DIR: "results/standard/11_resnet50_3d"
