DATA:
  ROOT: "datasets"
  SESSION: "NOXI"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "SMOTE"
  NOXI_IMG_DATA: "noxi_tiny/img"
  NOXI_AUD_DATA: "noxi_tiny/wav"
  NOXI_LABEL_DATA: "noxi_tiny/label/noxi_sessions_label.pkl"
DATA_LOADER:
  # NAME: "bimodal_resnet_lstm_data_loader_udiva" 
  NAME: "bimodal_resnet_lstm_data_loader_noxi"
  # TRANSFORM: "udiva_frame_transforms"
  TRANSFORM: "face_image_transform"
  # TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 32
  VALID_BATCH_SIZE: 1
  TEST_BATCH_SIZE: 1
  NUM_WORKERS: 1
  DATASET_NAME: "NOXI"
  DROP_LAST: False
  PREFETCH_FACTOR: 2
  NUM_FOLD: 3
MODEL:
  # NAME: "resnet50_3d_model_udiva"                   # CNN 视觉: ResNet50_3D
  # NAME: "audio_resnet_udiva"                        # CNN 音频: ResNet18
  # NAME: "audiovisual_resnet_lstm_udiva"             # CNN 音频+视觉: ResNet18 + ResNet50_3D
  NAME: "visual_graph_representation_learning"      # GNN 视觉 图表示学习
  # NAME: "audio_graph_representation_learning"       # GNN 音频 图表示学习
  # NAME: "audiovisual_graph_representation_learning" # GNN 视觉+音频融合 图表示学习
  NUM_CLASS: 4
  AU_CLASS: [12,] # 列表结构，单模态时列表只有一个元素，多模态时有2个元素, 第一个元素是visual的AU个数，第二个元素是audio的元素个数。[12]: 12个au图节点; [8]:8个au图节点; [15]: 取并集15个au图节点; e.g. [12,8]: visual 取12个au图节点, audio 取8个au图节点
  BACKBONE_INPUT: 'frame' # frame:输入MEFARG backbone的数据是每一帧图像; video:输入MEFARG backbone的数据是每一段视频，即图像序列
  PREDICTION_FEAT: 'cl_edge' # 预测时使用的特征 cl:使用MEFARG返回的cl; cl_edge:使用MEFARG返回的cl_edge; f_v:使用MEFARG返回的f_v; f_e:使用MEFARG返回的f_e
LOSS:
  # NAME: "binary_cross_entropy" # binary outcome
  NAME: "cross_entropy" # single label, multiple classes refer: https://towardsdatascience.com/deep-learning-which-loss-and-activation-functions-should-i-use-ac02f1c56aa8
SOLVER:
  NAME: "adam"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [50, 100, 200, 300, 400, 500, 540, 550, 560, 570, 580, 590]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 2
  BIMODAL_OPTION: 1       # 1: visual 2: audio # 3: both
  # OUTPUT_DIR: "results/demo/unified_frame_images/bimodal_resnet_noxi"
  SAVED_MODEL_DIR: "saved_model/deeppersonality/bimodal_resnet_noxi_tiny"
  # SAVED_MODEL_DIR: "saved_model/deeppersonality/graph_visual_noxi_tiny"
  LOG_INTERVAL: 1
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
  ACC_THRESHOLD: 0.99
  # PRE_TRAINED_MODEL: "pre_trained_weights/ME-GraphAU/ME-GraphAU_swin_tiny_BP4D/MEFARG_swin_tiny_BP4D_fold1.pth"
  # PRE_TRAINED_MODEL: "pre_trained_weights/ME-GraphAU/ME-GraphAU_swin_tiny_BP4D/MEFARG_swin_tiny_BP4D_fold1.pth;pre_trained_weights/ME-GraphAU/ME-GraphAU_resnet50_DISFA/MEFARG_resnet50_DISFA_fold1.pth"
  # PRE_TRAINED_MODEL: "pre_trained_weights/ME-GraphAU/ME-GraphAU_resnet101_BP4D/MEFARG_resnet101_BP4D_fold1.pth;pre_trained_weights/ME-GraphAU/ME-GraphAU_resnet50_DISFA/MEFARG_resnet50_DISFA_fold1.pth"
  PRE_TRAINED_MODEL: "pre_trained_weights/ME-GraphAU/ME-GraphAU_resnet50_BP4D/MEFARG_resnet50_BP4D_fold1.pth;pre_trained_weights/ME-GraphAU/ME-GraphAU_resnet50_DISFA/MEFARG_resnet50_DISFA_fold1.pth"
  USE_AMP: True
  USE_HALF: False
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
