DATA:
  ROOT: "datasets"
  SESSION: "NOXI"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "SMOTE"
  NOXI_IMG_DATA: "noxi_full/img"
  NOXI_AUD_DATA: "noxi_full/wav"
  NOXI_LABEL_DATA: "noxi_full/label/noxi_sessions_label.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_lstm_data_loader_noxi"
  TRANSFORM: "face_image_transform"
  TRAIN_BATCH_SIZE: 64
  VALID_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 1
  DATASET_NAME: "NOXI"
  DROP_LAST: False
  PREFETCH_FACTOR: 2
  NUM_FOLD: 3
MODEL:
  # NAME: "resnet50_3d_model_udiva"                   # CNN 视觉: ResNet50_3D
  # NAME: "audio_resnet_udiva"                        # CNN 音频: ResNet18
  NAME: "audiovisual_resnet_lstm_udiva"             # CNN 音频+视觉: ResNet18 + ResNet50_3D
  NUM_CLASS: 4
LOSS:
  NAME: "cross_entropy" # single label, multiple classes refer: https://towardsdatascience.com/deep-learning-which-loss-and-activation-functions-should-i-use-ac02f1c56aa8
SOLVER:
  NAME: "adam"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [1, 2, 4, 6, 8, 10, 20, 100, 200, 300, 400, 500, 540, 550, 560, 570, 580, 590]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 2
  BIMODAL_OPTION: 3       # 1: visual 2: audio # 3: both
  SAVED_MODEL_DIR: "saved_model/deeppersonality/resnet18_noxi_full_audiovisual"
  LOG_INTERVAL: 10
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
  ACC_THRESHOLD: 0.45
  USE_AMP: False
  USE_HALF: False
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
