DATA:
  ROOT: "datasets"
  SESSION: "NOXI"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "SMOTE"
  NOXI_IMG_DATA: "noxi_full/img"
  NOXI_AUD_DATA: "noxi_full/wav"
  NOXI_LABEL_DATA: "noxi_full/label/noxi_sessions_label.pkl"
DATA_LOADER:
  # NAME: "bimodal_resnet_lstm_data_loader_udiva" 
  NAME: "bimodal_resnet_lstm_data_loader_noxi"
  TRANSFORM: "udiva_frame_transforms"
  TRAIN_BATCH_SIZE: 32
  VALID_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 1
  DATASET_NAME: "NOXI"
  DROP_LAST: False
  PREFETCH_FACTOR: 1
  NUM_FOLD: 5
MODEL:
  NAME: "resnet50_3d_model_udiva"         # 视觉: ResNet3D
  # NAME: "audio_resnet_udiva"            # 音频: 纯ResNet模型结构
  # NAME: "audiovisual_resnet_lstm_udiva" # 音频+视觉: ResNet-LSTM模型结构：加入了LSTM层处理视觉分支的图片特征序列
  NUM_CLASS: 4
LOSS:
  NAME: "binary_cross_entropy"
SOLVER:
  NAME: "adam"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [5, 10, 20, 100, 200, 300, 400, 500, 540, 550, 560, 570, 580, 590]
TRAIN:
  TRAINER: "BiModalTrainerUdiva"
  MAX_EPOCH: 1
  SAVED_MODEL_DIR: "saved_model/deeppersonality/resnet_3d_noxi"
  BIMODAL_OPTION: 1
  LOG_INTERVAL: 50
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
  ACC_THRESHOLD: 0.35
  CROSS_RESUME: "saved_model/deeppersonality/resnet_3d_noxi/03-30_02-21_sp32_bs32_ep5/checkpoint_fold0_acc0.3622_ep0.pkl"
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
