DATA:
  ROOT: "datasets"
  SESSION: "NOXI"
  SAMPLE_SIZE: 16
  # SAMPLING_NAME: "BorderlineSMOTE"
  # NOXI_IMG_DATA: "noxi_full/img"
  # NOXI_AUD_DATA: "noxi_full/wav"
  # NOXI_LABEL_DATA: "noxi_full/label/noxi_sessions_label.pkl"
  NOXI_IMG_DATA: "noxi_tiny/img"
  NOXI_AUD_DATA: "noxi_tiny/wav"
  NOXI_LABEL_DATA: "noxi_tiny/label/noxi_sessions_label.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_lstm_data_loader_noxi" 
  TRANSFORM: "face_image_transform"
  TRAIN_BATCH_SIZE: 32
  VALID_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 1
  DATASET_NAME: "NOXI"
  DROP_LAST: False
  PREFETCH_FACTOR: 2
  NUM_FOLD: 3
MODEL:
  # NAME: "vivit_model_udiva"  # visual: https://github.com/rishikksh20/ViViT-pytorch
  # NAME: "vivit_model3_udiva" # visual: https://github.com/drv-agwl/ViViT-pytorch
  # NAME: "timesformer_udiva"  # visual: https://github.com/facebookresearch/TimeSformer
  NAME: "ssast_udiva"          # audio: https://github.com/YuanGongND/ssast
  NUM_CLASS: 4
LOSS:
  NAME: "cross_entropy"
SOLVER:
  NAME: "ssast_adam"
  SCHEDULER: "reduce_lr_on_plateau"
  LR_INIT: 0.0001
  WEIGHT_DECAY: !!float 5e-7
  BETA_1: 0.95
  BETA_2: 0.999
  MODE: 'max'
  FACTOR: 0.5
  LR_PATIENCE: 2
TRAIN:
  TRAINER: "SSASTTrainer"
  MAX_EPOCH: 2
  BIMODAL_OPTION: 2  # 1: visual 2: audio # 3: both
  SAVED_MODEL_DIR: "saved_model/deeppersonality/transformer_noxi_audio_pretrain"
  LOG_INTERVAL: 10
  VALID_INTERVAL: 1
  TEST_INTERVAL: 1
  PRE_TRAINED_MODEL: "./pre_trained_weights/SSAST/save_mask01-tiny-f16-t16-epo300-lr0.0005-m400-pretrain_mpc-udiva/models/best_audio_model.pth"
  USE_AMP: True
  USE_HALF: False
TEST:
  COMPUTE_PCC: False
  COMPUTE_CCC: False
