DATA:
  TRAIN_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_pred_output/statistic_train_data.pkl"
  VALID_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_pred_output/statistic_valid_data.pkl"
  TEST_IMG_DATA: "datasets/stage_two/deep_bimodal_reg_pred_output/statistic_test_data.pkl"
DATA_LOADER:
  NAME: "statistic_data_loader"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "statistic_mlp"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  MILESTONE: [2000, 2500]
TRAIN:
  TRAINER: "StatisticTrainer"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results_second_stage/statistic/01_deep_bimodal_statistic"
